version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    links:
       - redis:redis
    depends_on:
       - redis
    expose:
       - 8000
    user: 1002:1003 ## needed for linux
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:latest
    expose:
        - 6379

  nginx:
    build: ./mysite/nginx/
    ports:
      - 80:80
    links:
      - web:web
    depends_on:
      - web
