# Generated by Django 4.0.4 on 2022-05-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KingdomCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Card_Name', max_length=250)),
                ('Set', models.CharField(default='Card_Set', max_length=240)),
                ('Types', models.CharField(default='Card_Type', max_length=240)),
                ('Cost', models.CharField(default='0', max_length=20)),
                ('Actions', models.CharField(default='0', max_length=20)),
                ('Cards', models.CharField(default='0', max_length=20)),
                ('Buys', models.CharField(default='0', max_length=20)),
                ('Coins', models.CharField(default='0', max_length=20)),
                ('Trash', models.CharField(default='0', max_length=20)),
                ('Exile', models.CharField(default='0', max_length=20)),
                ('Junk', models.CharField(default='0', max_length=20)),
                ('Gain', models.CharField(default='0', max_length=20)),
                ('Victory_Points', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NamesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=50)),
            ],
        ),
    ]
